version: 2
jobs:
  test:
    docker:
      - image: dataworld/pyenv-tox

    working_directory: /root/target-datadotworld

    steps:
      - checkout

      - restore_cache:
          keys:
            - tox_cache-{{ checksum "tox.ini" }}

      - run:
          name: pyenv setup
          command: |
            pyenv local 3.6.0

      - run:
          name: tox
          command: tox --pre

      - persist_to_workspace:
          root: .
          paths:
            - ./*

      - save_cache:
          key: tox_cache-{{ checksum "tox.ini" }}
          paths:
            - .eggs
            - .tox

  pypi-release:

    docker:
      - image: dataworld/pyenv-tox

    working_directory: /root/target-datadotworld

    steps:
      - attach_workspace:
          at: /root/target-datadotworld

      - run:
          name: build dist
          command: python setup.py sdist bdist_wheel --universal

      - deploy:
          name: pypi release
          command: twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

  docker-release:
    docker:
      - image: dataworld/pyenv-tox

    working_directory: /root/target-datadotworld

    steps:
      - attach_workspace:
          at: /root/target-datadotworld

      - run:
          name: define PACKAGE_VERSION
          command: |
            echo "export PACKAGE_VERSION=$(python -c "import pkg_resources; print(pkg_resources.get_distribution('target-datadotworld').version)")" >> $BASH_ENV
            source $BASH_ENV

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: docker setup
          command: curl -sSL https://get.docker.com/ | sh

      - run:
          name: docker build
          command: docker build -t dataworld/target-datadotworld -t dataworld/target-datadotworld:$PACKAGE_VERSION .

      - deploy:
          name: docker-hub release
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dataworld/target-datadotworld:latest
            docker push dataworld/target-datadotworld:$PACKAGE_VERSION

workflows:
  version: 2
  test-double-release:
    jobs:
      - test
      - pypi-release:
          filters:
            branches:
              only:
                - release
          requires:
            - test
      - docker-release:
          filters:
            branches:
              only:
                - release
          requires:
            - test